### ISSUE TITLE
Minor framework path issue

### ISSUE THREAD

**Issue by MarkSiedle** [daltoniam/Skeets#1]
Hi, thanks for your work on this library. One minor thing you may want to remove ...there's a local framework path reference that was causing me issues on install.

![screen shot 2015-01-11 at 9 15 41 am](https://cloud.githubusercontent.com/assets/819605/5693659/099422e8-9973-11e4-88ef-af5777a982f8.png)

Cheers
Mark

**Comment by daltoniam** [comment]
Nice catch and thank you!
