### ISSUE TITLE
No such module 'SwiftHTTP'

### ISSUE THREAD

**Issue by Mar3h** [daltoniam/Skeets#10]
Unable to build the project on Xcode 6.3 and 6.3.1
SwiftHTTP already added

![screen shot 2015-04-27 at 8 57 53 am](https://cloud.githubusercontent.com/assets/4371268/7340649/4a25e322-ecbc-11e4-9c22-17320bee0dce.png)
![screen shot 2015-04-27 at 8 57 28 am](https://cloud.githubusercontent.com/assets/4371268/7340651/4eec936a-ecbc-11e4-95a6-952c8671f3bb.png)

**Comment by daltoniam** [comment]
yeah this one of the sore spots of xCode and frameworks. There isn't a great way to make the project build the SwiftHTTP project before the Skeets project without modifying the Skeets project. All that being said, you can make SwiftHTTP be a linked framework in the skeets project to get it working.

(pictures for added clarity)
![screen shot 2015-04-27 at 8 45 15 am](https://cloud.githubusercontent.com/assets/905059/7351431/fbf4a456-ecb9-11e4-83c1-fa53fb63f0ae.png)
![screen shot 2015-04-27 at 8 44 53 am](https://cloud.githubusercontent.com/assets/905059/7351435/fff113d2-ecb9-11e4-98c6-6fdbefe41690.png)

**Comment by Mar3h** [comment]
Thank you very much.
I can build the project now
