### ISSUE TITLE
Failure doesnt execute if no internet

### ISSUE THREAD

**Issue by sladjannimcevic** [daltoniam/Skeets#12]
![5866167edcfec96e02075d6fed76f1944e4c9b19a025c37ee0 pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/8166471/7493661/197f4882-f403-11e4-96c5-7ab5a042754f.jpg)

Thank you for your work.
Println never executed if there is no internet. Am i doing something wrong?

**Comment by sladjannimcevic** [comment]
O its because backgroundsession. I changed to default session and now its working as i want. Again, ty for your work!

**Comment by daltoniam** [comment]
:+1: glad it helps out.
