### ISSUE TITLE
Crashes When given Invalid URL

### ISSUE THREAD

**Issue by mahmed8003** [daltoniam/Skeets#2]
Let suppose we have URL like this that have space in it, 
"http://www.clickreadshare.com/wp-content/uploads/bunny-on-a-bed-big .jpg"

Library return an error like this:
fatal error: unexpectedly found nil while unwrapping an Optional value

``` swift
return self.requestSerializer.createRequest(NSURL(string: urlVal)!,
            method: method, parameters: parameters)
    }
```

I think URL encode needs to be added.

**Comment by daltoniam** [comment]
Good catch, was a bug in SwiftHTTP as you noted above. I checked in a fix that should protect when invalid url is requested.
