### ISSUE TITLE
404

### ISSUE THREAD

**Issue by aryanbaghi** [daltoniam/Skeets#23]
When image is not exist on server Skeets crash and trap in exception:

```
NSLocalizedDescription=The requested URL was not found on this server.}
fatal error: unexpectedly found nil while unwrapping an Optional value
```

**Comment by daltoniam** [comment]
Interesting, I haven't seen that in my testing. Can you provide an example to reproduce the issue?

**Comment by aryanbaghi** [comment]
Please test this url: 
    http://images.khabaronline.ir/images/2015/8/position50/2015_8_9_20_12_14.jpg

It is interesting, on some non exist image url it work but on some like this it not work.
If it work on your test please try to again to load from cache may problem is on cache!
Thank you

**Comment by aryanbaghi** [comment]
@daltoniam I think when response is html page this error happen!
By the way this is another example:
http://www.sakhtafzarmag.com/images/Summer-94/Game%252520Stuff/ten.jpg

**Comment by daltoniam** [comment]
Ok good to know, thanks. I haven't had a chance to look into it yet, but I will certainly take into that account.

**Comment by aryanbaghi** [comment]
Fixed in merge request!
