### ISSUE TITLE
Hash conflict

### ISSUE THREAD

**Issue by aryanbaghi** [daltoniam/Skeets#25]
I think you should change hash function because this is an example that have same hash so load wrong image:
http://media.isna.ir/content/1423553719742_IMAGE11423544834450.jpg/4
http://www.ana.ir/Media/Image/1394/05/30/635757572028226569.jpg

**Comment by daltoniam** [comment]
I agree. This isn't the first time There has been hash related issues reported in the past. seen an issue. I think we should probably move our to a better hash function like MD5.

**Comment by aryanbaghi** [comment]
What happend if we just remove http://  and replace `/` with `@`  instead of hashing? I think if we use hash we should handle conflict.

**Comment by daltoniam** [comment]
Yeah that would work fine. I was just suggesting MD5 since it was builtin, but it looks like you already had a simpler solution with #27!
