### ISSUE TITLE
Swift-2.0: advance unavailable

### ISSUE THREAD

**Issue by niwakame** [daltoniam/Skeets#29]
Seems like advance is deprecated in Swift 2.0, leading to errors here:
ImageManager.swift:
[Line 180&181](https://github.com/daltoniam/Skeets/blob/swift-2.0/ImageManager.swift#L180)
[Line 206](https://github.com/daltoniam/Skeets/blob/swift-2.0/ImageManager.swift#L206)

Error: 'advance' is unavailable: call the 'advanceBy(n)'  method on the index

Xcode 7.0 (iOS 9)

**Comment by daltoniam** [comment]
Since this is a duplicate report of #28 we will merge them.
