### ISSUE TITLE
Invalid Skeets.podspec

### ISSUE THREAD

**Issue by valzevul** [daltoniam/Skeets#5]
Get the following problem using CocoaPods (0.36.0.beta.2).

```
[!] Invalid `Skeets.podspec` file: undefined method `dependency=' for #<Pod::Specification name="Skeets">. Updating CocoaPods might fix the issue.

source 'https://github.com/CocoaPods/Specs.git'
 #  from /Users/valzevul/projects/SkeetsExample/Pods/Skeets/Skeets.podspec:11
 #  -------------------------------------------
 #    s.source_files = '*.{h,swift}'
 >    s.dependency   = 'SwiftHTTP'
 #  end
 #  -------------------------------------------
```

Is this a problem of Skeets.podspec or CocoaPods problem?

**Comment by daltoniam** [comment]
I am still trying to work out the dependency for the two platforms and all of that :smile:. I updated the podspec to work on iOS (I hope). I am still trying to figure out how to support the different module/framework name on OS X. Let me know how it works.

**Comment by daltoniam** [comment]
I got this sorted out for OS X, should be good to go.

**Comment by danwetherald** [comment]
Still getting this issue

**Comment by daltoniam** [comment]
I forgot to update the tag, it is now updated.

**Comment by danwetherald** [comment]
I am still getting same error do i need to do anything before i do another pod install?

**Comment by daltoniam** [comment]
Sorry forgot to push the podspec, try one more time please.

**Comment by danwetherald** [comment]
New Error:

dan0034001$ pod init
dan0034001$ pod install
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
Analyzing dependencies
Pre-downloading: `Skeets` from `https://github.com/daltoniam/skeets.git`, tag `0.9.1`
Pre-downloading: `SwiftHTTP` from `https://github.com/daltoniam/SwiftHTTP.git`, tag `0.9.1`
[!] Unable to satisfy the following requirements:
- `SwiftHTTP (from`https://github.com/daltoniam/SwiftHTTP.git`, tag `0.9.1`)`required by`Podfile`
- `SwiftHTTP (from`https://github.com/daltoniam/SwiftHTTP.git`, tag `0.9.1`)`required by`Podfile`
- `SwiftHTTP (~> 0.9.2)` required by `Skeets (0.9.1)`

**Comment by danwetherald** [comment]
got it, im new to cocopods, i commented out the already installed SwiftHTTP

**Comment by daltoniam** [comment]
Sweet, good to know. Not sure if that is a bug in the beta or not. The whole Swift pods are still really new to us all :smile:

**Comment by danwetherald** [comment]
Thanks for your super fast response and help!
