### ISSUE TITLE
fatal error: unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by Joropo** [daltoniam/Skeets#8]
Here's a screen shot of the error, i'm not sure why this is happening.
![screen shot 2015-03-15 at 8 51 22 pm](https://cloud.githubusercontent.com/assets/4211917/6660388/187e2876-cb55-11e4-9f19-380f5739fd52.png)

**Comment by daltoniam** [comment]
Interesting. I will see if I can reproduce it. Is there a specific url or steps you can use to create the issue?

**Comment by Joropo** [comment]
it happens when trying to fetch images to populate UICollectionview cells

**Comment by daltoniam** [comment]
Tag 0.9.3 should resolve this issue.

**Comment by Joropo** [comment]
I tried to update Cocoapods via pod update, but i got an error.

**Comment by daltoniam** [comment]
What is the error? It worked ok for me in my test project.

**Comment by Joropo** [comment]
target 'FestFeed' do
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'SwiftHTTP', '~> 0.9.2'
pod 'Skeets', '~> 0.9.3’
end

```

### Error

```

SyntaxError - /Users/Me/Documents/Project/Podfile:10: unterminated string meets end of file

**Comment by daltoniam** [comment]
Not sure why you are seeing that. Here is an example podfile.

https://github.com/Vluxe/SwiftPeople/blob/master/Podfile

**Comment by daltoniam** [comment]
Where you able to get this sorted out?
